#pricestore.azurecr.io/pricestore/main-api:v1
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: main-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
      - name: main-api
        image: pricestore.azurecr.io/pricestore/main-api:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ConnectionStrings__MongoConnection
          value: mongodb://mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: main-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: main-api