version: '3.1'

services:  
  price-stores:  
    image: pricestore.azurecr.io/pricestore/main-api:v1
    ports: 
      - "80:80"
    secrets:
      - mongo_connection    

secrets:
  mongo_connection:
    external: true
# Use secrets after DONT FORGET!
#     secrets:
#       - mongo_connection

# secrets:
#   - mongo_connection:
#     external: true

  
