version: '3.1'

services:  
  price-stores:  
    build: .
    ports: 
      - "5001:80"
    depends_on:
      - mongo
    environment:
      ConnectionStrings__MongoConnection=mongodb://mongo:27017
  mongo:
    image: "mongo"
    ports: 
      - "27017:27017"
  
