version: '3.3'

services:  
  price-stores:
    image: rafaelmiceli/pricestore
    ports:  
      - "5001:80"
    depends_on:
      - mongo
    environment:
      - ConnectionStrings__MongoConnection=mongodb://mongo:27017
    # network:
    #   - pricestore
  mongo:
    image: "mongo"
    ports: 
      - "27017:27017"
    # network:
    #   - pricestore
  
# network:
#   pricestoredocker