version: '3.1'

services:  
  price-stores:  
    build: .
    ports: 
      - "5001:80"
    environment:
      - ConnectionStrings__MongoConnection=mongodb:conn
# Use secrets after DONT FORGET!
#     secrets:
#       - mongo_connection

# secrets:
#   - mongo_connection:
#     external: true

  
